language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
services: mongodb
matrix:
  fast_finish: true
  allow_failures:
     - php: nightly
before_script:
  - composer self-update
  - yes '' | pecl install -f mongodb-1.1
  - composer install
script: ./vendor/bin/phpunit --coverage-clover clover.xml
after_success: ./vendor/bin/coveralls -v
